### ISSUE TITLE
A question about model loading

### ISSUE THREAD

**Issue by wangzhaoyang-508** [OpenGVLab/PIIP#2]
The congfig file needs to fill in the pre-trained weight paths of multiple branches, but the downloaded ckpt file is only one. How can I load it?

**Comment by yangxue0827** [comment]
The pre-trained weights of multiple branches should be downloaded from below, according to the config you selected.
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/ae29d19a-3f48-4b6f-865e-acd46b7dd12c">

**Comment by yangxue0827** [comment]
I guess what you downloaded are trained weights, not pre-trained weights.

**Comment by wangzhaoyang-508** [comment]
> I guess what you downloaded are trained weights, not pre-trained weights.

Yes I want to evaluate the trained weights, how can I load them?

**Comment by yangxue0827** [comment]
https://github.com/OpenGVLab/PIIP/tree/main/mmdetection

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/75bbf4ff-ed89-4863-9ef3-0a47ef9aefe1">

**Comment by wangzhaoyang-508** [comment]
Sorry, I don't quite understand how to configure the trained weights in the 'config/piip/2branch/...py' file? I only see the pretrain path for each branch in 'config/piip/2branch/...py'.

**Comment by yangxue0827** [comment]
You don't need to modify the config.

**Comment by wangzhaoyang-508** [comment]
> You don't need to modify the config.

I still failed. My input command is:
"python tools/test.py configs/piip/3branch/dino_4scale_deit_384_sbl_1792_1120_672_fpn_3x_coco_bs32_ms.py ./work_dirs/1/dino_4scale_deit_384_sbl_1792_1120_672_fpn_3x_coco_bs32_ms.pth --eval bbox segm"

Error: " Traceback (most recent call last):
  File "/home/wzy/wang/PIIP-main/mmdetection/tools/test.py", line 289, in &lt;module&gt;
    main()
  File "/home/wzy/wang/PIIP-main/mmdetection/tools/test.py", line 227, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/wzy/wang/PIIP-main/mmdetection/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: DINO: PIIPThreeBranch: [Errno 2] No such file or directory: './pretrained/deit_3_large_384_21k.pth'"

**Comment by yangxue0827** [comment]
If you don not download the pretrained weight, you should set `pretrained=None` for all branches.

**Comment by wangzhaoyang-508** [comment]
sorry，When I set pretrained=None ,the error and log is:
```
python tools/test.py configs/piip/3branch/dino_4scale_deit_384_sbl_1792_1120_672_fpn_3x_coco_bs32_ms.py work_dirs/1/dino_4scale_deit_384_sbl_1792_1120_672_fpn_3x_coco_bs32_ms.pth --eval bbox segm
/home/wzy/wang/PIIP-main/mmcv/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
please install apex for fused_adamw
loading annotations into memory...
Done (t=0.24s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/wzy/wang/PIIP-main/mmdetection/mmdet/models/backbones/piip_3branch.py", line 71, in __init__
    if 'deit' in branch1['pretrained']:
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/wzy/wang/PIIP-main/mmdetection/mmdet/models/detectors/dino.py", line 15, in __init__
    super(DETR, self).__init__(*args, **kwargs)
  File "/home/wzy/wang/PIIP-main/mmdetection/mmdet/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/wzy/wang/PIIP-main/mmdetection/mmdet/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: PIIPThreeBranch: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wzy/wang/PIIP-main/mmdetection/tools/test.py", line 289, in <module>
    main()
  File "/home/wzy/wang/PIIP-main/mmdetection/tools/test.py", line 227, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/wzy/wang/PIIP-main/mmdetection/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wzy/wang/PIIP-main/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: DINO: PIIPThreeBranch: argument of type 'NoneType' is not iterable




```

**Comment by yangxue0827** [comment]
Don't modify pretrained yet. Instead, download the required pretrained weights.

**Comment by wangzhaoyang-508** [comment]
> Don't modify pretrained yet. Instead, download the required pretrained weights.

During inference, mmdetection did not load the weight path parameter entered in the command line, but loaded the pre-trained path in the config file, resulting in an evaluation result of 0. Why is this?

**Comment by wangzhaoyang-508** [comment]
Do I need to use some method from mmcv_custom?

**Comment by wangzhaoyang-508** [comment]
> Do I need to use some method from mmcv_custom?

I think I can successfully evaluate it. The previous problem may be that I did not set any additional settings or turn off deepspeed when using a single 4090.
